use_frameworks!

#source 'https://github.com/CocoaPods/Specs.git'
#source 'http://121.41.108.203/sangshen/MCLocationManager.git'

platform :ios, '8.0'

target 'CSSTracker_Example' do
  pod 'CSSTracker', :path => '../'

  target 'CSSTracker_Tests' do
    inherit! :search_paths

    
  end
end
